services:
  mysql:
    container_name: mysql-Restaurant
    image: mysql
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATA: /var/lib/mysql/data
      MYSQL_DB: Restaurant

    volumes:
      - mysql:/var/lib/mysql/data
    ports:
      - 3306:3306
    networks:
      - spring-Restaurant
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-Restaurant
    image: maildev/maildev
    ports:
      - 2025:2025
      - 1080:1080

networks:
  spring-Restaurant:
    driver: bridge

volumes:
  mysql:
    driver: local